package code.model

import net.liftweb._
import util._
import common._
import http._

import net.liftweb.mapper._
import net.liftweb.util._
import net.liftweb.common._
import scala.xml._

object Country extends Country with LongKeyedMetaMapper[Country] with Loggable {

  override def dbTableName = "t_country"

  override def dbAddTable = Full(populate _)

  private def populate {
    //if (Country.count == 0) {
      logger.info("Populating Province Table ...%s".format(Country.count))
      Country.create.id(1).name("USA").sort(1).save()
      Country.create.id(2).name("China").sort(2).save()
    //}
  }

}

class Country extends LongKeyedMapper[Country] with OneToMany[Long, Country] {

  def getSingleton = Country

  def primaryKeyField = id

  object id extends MappedLongIndex(this) {
    override def dbColumnName = "country_id"
    override def writePermission_? = true // if u want to set it via your code, keep this true
    override def dbAutogenerated_? = false
    override def dbIndexed_? = true
    override def dbNotNull_? = true
  }

  object name extends MappedString(this, 100) {
    override def displayName = S.?("country.name")
  }

  object sort extends MappedInt(this) {
    override def dbColumnName = "sort"
  }

  object cities extends MappedOneToMany(City, City.country, OrderBy(City.sort, Ascending)) {

  }

}